version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db1
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: redis-db1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  mysql-data:
  redis-data:
